// taro-weapp/src/pages/login/index.tsx
import { View, Text, Input } from '@tarojs/components'
import Taro from '@tarojs/taro'
import { useState } from 'react'
import './index.scss'

export default function Login() {
  const [studentId, setStudentId] = useState('2021004562')
  const [password, setPassword] = useState('password')
  const [showPassword, setShowPassword] = useState(false)

  const handleLogin = () => {
    // 模拟登录，跳转到首页
    Taro.switchTab({ url: '/pages/home/index' })
  }

  return (
    <View className='login-page'>
      {/* 背景点阵 */}
      <View className='dot-pattern' />

      <View className='login-content'>
        {/* Logo */}
        <View className='logo-section'>
          <View className='logo-box'>
            <View className='logo-inner'>
              <Text className='iconfont icon-school' />
            </View>
          </View>
          <View className='logo-text'>
            <Text className='app-title'>Zhiwai Assistant</Text>
            <Text className='app-subtitle'>欢迎回来，请登录继续</Text>
          </View>
        </View>

        {/* 表单 */}
        <View className='form-section'>
          <View className='input-group'>
            <View className='input-icon'>
              <Text className='iconfont icon-badge' />
            </View>
            <Input
              className='input-field'
              placeholder='学号 / Student ID'
              value={studentId}
              onInput={(e) => setStudentId(e.detail.value)}
            />
          </View>

          <View className='input-group'>
            <View className='input-icon'>
              <Text className='iconfont icon-lock' />
            </View>
            <Input
              className='input-field'
              placeholder='密码 / Password'
              password={!showPassword}
              value={password}
              onInput={(e) => setPassword(e.detail.value)}
            />
            <View className='toggle-password' onClick={() => setShowPassword(!showPassword)}>
              <Text className={`iconfont ${showPassword ? 'icon-visibility-off' : 'icon-visibility'}`} />
            </View>
          </View>

          <View className='forgot-password'>
            <Text>忘记密码?</Text>
          </View>
        </View>

        {/* 按钮 */}
        <View className='button-section'>
          <View className='btn-login' onClick={handleLogin}>
            <Text>登录</Text>
          </View>
          <View className='btn-register'>
            <Text>注册</Text>
          </View>
        </View>

        {/* 底部协议 */}
        <View className='footer-text'>
          <Text>登录即代表您同意 </Text>
          <Text className='link'>服务条款</Text>
          <Text> & </Text>
          <Text className='link'>隐私政策</Text>
        </View>
      </View>
    </View>
  )
}

// xisu-uniapp/src/pages/login/index.vue
<template>
	<view class="login-page">
		<!-- 点阵背景 -->
		<view class="dot-pattern"></view>

		<view class="login-content">
			<!-- Logo区域 -->
			<view class="logo-section">
				<view class="logo-box">
					<view class="logo-inner">
						<text class="iconfont icon-school"></text>
					</view>
				</view>
				<view class="logo-text">
					<text class="app-title">知外助手</text>
					<text class="app-subtitle">欢迎回来，请登录继续</text>
				</view>
			</view>

			<!-- 表单区域 -->
			<view class="form-section">
				<view class="input-group">
					<view class="input-wrapper">
						<view class="input-icon">
							<text class="iconfont icon-assignment_ind"></text>
						</view>
						<input 
							class="input-field" 
							type="text" 
							v-model="studentId"
							placeholder="学号 / Student ID" 
							placeholder-class="placeholder"
						/>
					</view>

					<view class="input-wrapper">
						<view class="input-icon">
							<text class="iconfont icon-flight_class"></text>
						</view>
						<input 
							class="input-field" 
							type="text"
							:password="!showPassword"
							v-model="password"
							placeholder="密码 / Password" 
							placeholder-class="placeholder"
						/>
						<view class="toggle-password" @tap="showPassword = !showPassword">
							<text class="iconfont" :class="showPassword ? 'icon-visibility' : 'icon-visibility_off'"></text>
						</view>
					</view>

					<view class="forgot-password">
						<text class="forgot-link">忘记密码?</text>
					</view>
				</view>

				<view class="button-group">
					<button class="btn-primary" @tap="handleLogin">
						登录
					</button>
					<button class="btn-outline" @tap="handleRegister">
						注册
					</button>
				</view>
			</view>

			<!-- 底部协议 -->
			<view class="footer-text">
				<text class="agreement">
					登录即代表您同意 
					<text class="link">服务条款</text> 
					& 
					<text class="link">隐私政策</text>
				</text>
			</view>
		</view>
	</view>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { authApi, saveTokens, saveUserInfo, getAccessToken, getUserInfo } from '@/services/apiService';

const studentId = ref('');
const password = ref('');
const showPassword = ref(false);
const isLoading = ref(false);

// 检查是否已登录
onMounted(() => {
	const token = getAccessToken();
	const user = getUserInfo();
	if (token && user) {
		// 已登录，跳转到首页
		uni.switchTab({ url: '/pages/home/index' });
	}
});

const handleLogin = async () => {
	if (!studentId.value) {
		uni.showToast({ title: '请输入学号', icon: 'none' });
		return;
	}
	if (!password.value) {
		uni.showToast({ title: '请输入密码', icon: 'none' });
		return;
	}
	
	isLoading.value = true;
	uni.showLoading({ title: '登录中...' });
	
	try {
		const res = await authApi.login({
			studentId: studentId.value,
			password: password.value,
		});
		
		// 保存登录凭证和用户信息
		saveTokens({
			accessToken: res.accessToken,
			refreshToken: res.refreshToken,
		});
		saveUserInfo(res.user);
		
		uni.hideLoading();
		uni.showToast({ title: '登录成功', icon: 'success' });
		
		setTimeout(() => {
			uni.switchTab({ url: '/pages/home/index' });
		}, 1000);
	} catch (error) {
		uni.hideLoading();
		const errorMessage = error instanceof Error ? error.message : '登录失败';
		uni.showToast({ title: errorMessage, icon: 'none', duration: 2000 });
	} finally {
		isLoading.value = false;
	}
};

const handleRegister = () => {
	uni.navigateTo({
		url: '/pages/register/index'
	});
};
</script>

<style lang="scss" scoped>
.login-page {
	position: relative;
	min-height: 100vh;
	background-color: $bg-light;
	overflow: hidden;
}

.dot-pattern {
	position: absolute;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;
	opacity: 0.4;
	background-image: radial-gradient(#9ca3af 2rpx, transparent 2rpx);
	background-size: 48rpx 48rpx;
	pointer-events: none;
}

.login-content {
	position: relative;
	z-index: 10;
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	min-height: 100vh;
	padding: 40rpx 48rpx;	padding-top: calc(var(--status-bar-height) + 120rpx);	box-sizing: border-box;
}

.logo-section {
	display: flex;
	flex-direction: column;
	align-items: center;
	margin-bottom: 80rpx;
}

.logo-box {
	width: 160rpx;
	height: 160rpx;
	border-radius: 32rpx;
	background-color: #fff;
	box-shadow: 0 20rpx 40rpx rgba(0,0,0,0.1);
	display: flex;
	align-items: center;
	justify-content: center;
	padding: 16rpx;
	margin-bottom: 32rpx;
}

.logo-inner {
	width: 100%;
	height: 100%;
	border-radius: 24rpx;
	background: linear-gradient(135deg, $primary 0%, #60A5FA 100%);
	display: flex;
	align-items: center;
	justify-content: center;
	
	.iconfont {
		font-size: 64rpx;
		color: #fff;
	}
}

.logo-text {
	display: flex;
	flex-direction: column;
	align-items: center;
}

.app-title {
	font-size: 48rpx;
	font-weight: 700;
	color: $text-primary;
	margin-bottom: 8rpx;
}

.app-subtitle {
	font-size: 28rpx;
	color: $text-secondary;
}

.form-section {
	width: 100%;
}

.input-group {
	margin-bottom: 40rpx;
}

.input-wrapper {
	position: relative;
	margin-bottom: 32rpx;
	
	&:last-child {
		margin-bottom: 0;
	}
}

.input-icon {
	position: absolute;
	left: 32rpx;
	top: 50%;
	transform: translateY(-50%);
	
	.iconfont {
		font-size: 40rpx;
		color: $text-light;
	}
}

.input-field {
	width: 100%;
	height: 112rpx;
	border-radius: 24rpx;
	border: 2rpx solid $border-color;
	background-color: #fff;
	padding-left: 96rpx;
	padding-right: 96rpx;
	font-size: 32rpx;
	color: $text-primary;
	box-sizing: border-box;
	
	&:focus {
		border-color: $primary;
	}
}

.placeholder {
	color: $text-light;
}

.toggle-password {
	position: absolute;
	right: 0;
	top: 0;
	width: 96rpx;
	height: 112rpx;
	display: flex;
	align-items: center;
	justify-content: center;
	
	.iconfont {
		font-size: 40rpx;
		color: $text-light;
	}
}

.forgot-password {
	display: flex;
	justify-content: flex-end;
	margin-top: 16rpx;
}

.forgot-link {
	font-size: 28rpx;
	color: $text-secondary;
}

.button-group {
	display: flex;
	flex-direction: column;
	gap: 24rpx;
}

.btn-primary {
	width: 100%;
	height: 112rpx;
	border-radius: 24rpx;
	background-color: $primary;
	color: #fff;
	font-size: 32rpx;
	font-weight: 700;
	display: flex;
	align-items: center;
	justify-content: center;
	border: none;
	box-shadow: 0 16rpx 32rpx rgba(59, 130, 246, 0.3);
	
	&:active {
		transform: scale(0.98);
		opacity: 0.9;
	}
}

.btn-outline {
	width: 100%;
	height: 112rpx;
	border-radius: 24rpx;
	background-color: transparent;
	color: $primary;
	font-size: 32rpx;
	font-weight: 700;
	display: flex;
	align-items: center;
	justify-content: center;
	border: 2rpx solid $primary;
	
	&:active {
		background-color: rgba(59, 130, 246, 0.05);
	}
}

.footer-text {
	margin-top: auto;
	padding-top: 80rpx;
}

.agreement {
	font-size: 24rpx;
	color: $text-light;
	text-align: center;
}

.link {
	text-decoration: underline;
	color: $text-secondary;
}
</style>
